import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "@/consts/schema"; // generated by openapi-typescript

const baseUrl = "https://api.realworld.show/api";

export const fetchClient = createFetchClient<paths>({ baseUrl });

export const $api = createClient(fetchClient);

export default fetchClient;
