import createFetchClient, { Middleware } from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "@/consts/schema"; // generated by openapi-typescript
import { getSession } from "./session";

// const baseUrl = "https://api.realworld.show/api";
const baseUrl = process.env.API_ENDPOINT

export const fetchClient = createFetchClient<paths>({ baseUrl });

const myMiddleware: Middleware = {
    async onRequest({ request, options }) {
        const token = await getSession()

        if (token) {
            request.headers.set("Authorization", `Token ${token}`);
        }
        return request;
    },
    async onResponse({ request, response, options }) {
        // const { body, ...resOptions } = response.clone();
        // console.log(resOptions)
        // // change status of response
        // return new Response(body, { ...resOptions, status: resOptions.status || 400 });

        return response.clone()
    },
    async onError({ error }) {
        return new Error("Oops, fetch failed", { cause: error });
        // wrap errors thrown by fetch
        // onError({ error }) {
        //     return new Error("Oops, fetch failed", { cause: error });
        // },
    },
};

fetchClient.use(myMiddleware)

export const $api = createClient(fetchClient);

export default fetchClient;
